[package]
name = "eml-nl"
version = "0.6.0"
edition = "2024"
license = "EUPL-1.2"
rust-version = "1.95" # MSRV
description = "Parse, manipulate and emit EML_NL documents"
documentation = "https://docs.rs/eml-nl"
repository = "https://github.com/kiesraad/rust-eml-nl"
homepage = "https://github.com/kiesraad/rust-eml-nl"

[features]
default = []
bin-utils = ["dep:clap", "dep:anyhow", "dep:tokio", "dep:tracing-subscriber", "dep:sha2"]

[[bin]]
name = "eml-validator"
path = "bin/eml-validator.rs"
required-features = ["bin-utils"]

[[bin]]
name = "eml2csv"
path = "bin/eml2csv.rs"
required-features = ["bin-utils"]

## This project attempts to minimize the dependencies used as much as possible.
## Where dependencies were used, they must have very high adoption in the Rust
## ecosystem and be actively maintained.
[dependencies]
# Used for simpler error handling and reporting
thiserror = { version = "2.0", default-features = false }
# Used as our XML parsing library
quick-xml = "0.40.0"
# Used for logging and diagnostics
tracing = { version = "0.1.43", default-features = false }
# Used for date and time handling
chrono = { version = "0.4.42", features = ["std"], default-features = false }
# Used for regular expressions that test input values
regex = { version = "1.12.2", default-features = false, features = ["std", "unicode"] }

## Optional dependencies used for utility binaries
# Used for command-line argument parsing
clap = { version = "4.5.54", optional = true, features = ["derive"]}
# Used for error handling in binaries
anyhow = { version = "1.0.100", optional = true , default-features = false }
# Used as the async runtime in binaries
tokio = { version = "1.49.0", optional = true, features = ["io-std", "io-util", "fs", "macros", "rt-multi-thread"]}
# Used for emitting logging in binaries
tracing-subscriber = { version = "0.3.22", optional = true, default-features = false, features = ["fmt", "env-filter"] }
# Used for SHA-256 hashing of EML files (in validator)
sha2 = { version = "0.11.0", optional = true , default-features = false }

[dev-dependencies]
# For showing much nicer diffs in test assertions
pretty_assertions = "1.4.1"
